"""Generate src/kws_params.h from a model_meta.json.

Firmware constants are generated, never transcribed. The device needs 26 floats
of per-coefficient normalisation plus four quantisation constants; hand-copying
those is exactly how a silent train/inference mismatch enters, and it would not
crash -- it would quietly degrade accuracy.

Usage:
    python tools/emit_params.py <modeldir> [out.h]

Example:
    python tools/emit_params.py model_cont src/kws_params.h
"""

import io
import json
import sys

NL = "\n"


def main():
    mdir = sys.argv[1] if len(sys.argv) > 1 else "model_cont"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/kws_params.h"
    m = json.load(open(mdir + "/model_meta.json"))
    mean, std = m["mean"], m["std"]

    lines = [
        "// Auto-generated by tools/emit_params.py from %s/model_meta.json" % mdir,
        "// DO NOT EDIT BY HAND.",
        "#pragma once",
        "",
        "constexpr int KWS_N_FRAMES = %d;" % m["n_frames"],
        "constexpr int KWS_N_MFCC   = %d;" % m["n_mel"],
        "constexpr float KWS_IN_SCALE  = %.10ff;" % m["input_scale"],
        "constexpr int   KWS_IN_ZP     = %d;" % m["input_zero_point"],
        "constexpr float KWS_OUT_SCALE = %.10ff;" % m["output_scale"],
        "constexpr int   KWS_OUT_ZP    = %d;" % m["output_zero_point"],
        "",
        "// Per-coefficient normalisation. A single global mean/std collapsed",
        "// c2..c12 to std 0.04-0.08 and training degenerated to the majority",
        "// class (test accuracy 0.3846, exactly the silence fraction).",
        "constexpr float KWS_NORM_MEAN[%d] = {" % len(mean),
        "    " + ", ".join("%.8ff" % v for v in mean),
        "};",
        "constexpr float KWS_NORM_STD[%d] = {" % len(std),
        "    " + ", ".join("%.8ff" % v for v in std),
        "};",
    ]
    io.open(out, "w", encoding="utf-8", newline=NL).write(NL.join(lines) + NL)
    print("wrote %s" % out)
    print("  frames %d x mfcc %d | in scale %.8f zp %d | out scale %.8f zp %d"
          % (m["n_frames"], m["n_mel"], m["input_scale"], m["input_zero_point"],
             m["output_scale"], m["output_zero_point"]))
    print("  %d normalisation coefficients" % len(mean))


if __name__ == "__main__":
    main()
