// Auto-generated by tools/emit_params.py from model_bal/model_meta.json
// DO NOT EDIT BY HAND.
#pragma once

constexpr int KWS_N_FRAMES = 49;
constexpr int KWS_N_MFCC   = 13;
constexpr float KWS_IN_SCALE  = 0.0763322487f;
constexpr int   KWS_IN_ZP     = 36;
constexpr float KWS_OUT_SCALE = 0.0727806091f;
constexpr int   KWS_OUT_ZP    = 11;

// Per-coefficient normalisation. A single global mean/std collapsed
// c2..c12 to std 0.04-0.08 and training degenerated to the majority
// class (test accuracy 0.3846, exactly the silence fraction).
constexpr float KWS_NORM_MEAN[13] = {
    93.81809235f, 10.53957844f, -0.37082019f, 3.25811601f, 0.47771430f, 0.67043990f, -0.57339120f, 0.32321963f, 0.40546995f, 0.01590402f, 0.48725298f, -0.31527227f, 0.43934092f
};
constexpr float KWS_NORM_STD[13] = {
    14.47210217f, 5.10586166f, 2.80447125f, 2.97767735f, 2.00292611f, 1.94599760f, 1.84447372f, 1.50476933f, 1.29911387f, 1.43394995f, 1.25246072f, 1.15234566f, 1.13743758f
};
