// Auto-generated by tools/emit_params.py from model_mined/model_meta.json
// DO NOT EDIT BY HAND.
#pragma once

constexpr int KWS_N_FRAMES = 49;
constexpr int KWS_N_MFCC   = 13;
constexpr float KWS_IN_SCALE  = 0.0782364011f;
constexpr int   KWS_IN_ZP     = 35;
constexpr float KWS_OUT_SCALE = 0.0569627360f;
constexpr int   KWS_OUT_ZP    = -12;

// Per-coefficient normalisation. A single global mean/std collapsed
// c2..c12 to std 0.04-0.08 and training degenerated to the majority
// class (test accuracy 0.3846, exactly the silence fraction).
constexpr float KWS_NORM_MEAN[13] = {
    96.33671570f, 6.69660616f, 0.75602067f, 2.65653634f, 0.75862926f, 0.35185927f, -0.66266745f, 0.15931581f, 0.30682185f, 0.01084928f, 0.46044517f, -0.04865151f, 0.42113411f
};
constexpr float KWS_NORM_STD[13] = {
    14.37059975f, 6.27620411f, 2.86242700f, 3.03396225f, 1.95171404f, 1.84604609f, 1.79621875f, 1.42057407f, 1.25870490f, 1.35716605f, 1.21203268f, 1.11627114f, 1.09655857f
};
