// Auto-generated by tools/emit_params.py from model_aug/model_meta.json
// DO NOT EDIT BY HAND.
#pragma once

constexpr int KWS_N_FRAMES = 49;
constexpr int KWS_N_MFCC   = 13;
constexpr float KWS_IN_SCALE  = 0.0681439266f;
constexpr int   KWS_IN_ZP     = 32;
constexpr float KWS_OUT_SCALE = 0.0364325978f;
constexpr int   KWS_OUT_ZP    = -27;

// Per-coefficient normalisation. A single global mean/std collapsed
// c2..c12 to std 0.04-0.08 and training degenerated to the majority
// class (test accuracy 0.3846, exactly the silence fraction).
constexpr float KWS_NORM_MEAN[13] = {
    92.10640717f, 10.49642754f, -0.40101233f, 2.80392861f, 0.20882514f, 0.88115907f, -0.28213662f, 0.36346036f, 0.37782249f, 0.15859209f, 0.38469779f, -0.30272648f, 0.34653813f
};
constexpr float KWS_NORM_STD[13] = {
    16.46407890f, 5.47638941f, 3.01163077f, 2.92881656f, 2.18163705f, 1.95644486f, 1.84157765f, 1.55913949f, 1.35067523f, 1.38426149f, 1.28198099f, 1.18510807f, 1.15591216f
};
